[build]
  # Directory with the build output
  publish = "build"
  
  # Build command
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Increase Node.js memory limit for build
  NODE_VERSION = "22"
